/* 
 *  VisApp source file  
 *
 *  Release version: 1.1 December 2014
 *  File: VisApp/Plugins/TextImport/ImportTable.cpp
 *  Author: Paweu
 *  Header Date: Sun Dec  7 18:03:47 GMT 2014
 *
 */
/*--END OF HEADER BLOCK--*/
/*
Generated by "D:\CommandLine\csrc.bat"
On 2014-03-05 21:13:23,40
by Paweu
*/
#include "stdafx.h"
#include "TextImport.h"
