/* 
 *  VisApp source file  
 *
 *  Release version: 1.1 December 2014
 *  File: VisApp/core/src/Renderer/ShaderManager.h
 *  Author: Paweu
 *  Header Date: Sun Dec  7 18:03:47 GMT 2014
 *
 */
/*--END OF HEADER BLOCK--*/
/*
Generated by "D:\CommandLine\csrc.bat"
On 2014-03-12  6:42:46,77
by Paweu
*/

#pragma once
#ifndef ShaderManager_H
#define ShaderManager_H

namespace VisApp {
namespace Renderer { 
 
class ShaderManager {
public:
	ShaderManager();
	~ShaderManager();

	Shader* LoadDefaultShaderProgram();
	Shader* GetDefaultShader() {
		return LoadDefaultShaderProgram();
	}
protected:
	static GLuint LoadShaderCode(GLenum ShaderType, const char* CodeFileName);

private:
	//typedef std::list<Shader*> ShaderList;
	//ShaderList m_ShaderList;
	Shader *m_DefaultShader;
	ShaderManager(const ShaderManager&): m_DefaultShader(0) {}
};

} //namespace Renderer
} //namespace VisApp

#endif

